<html>
<head></head>
<body>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>Privacy Policy </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Matchon is a real-time audio and video chat application. You can meet new friends in India and enjoy happy time via our platform.<br /> When you use these services&mdash;and any others we roll out&mdash;you&rsquo;ll inevitably share some information with us. We get that that can affect your privacy. So we want to be upfront about the information we collect, how we use it, whom we share it with, and the choices we give you to control, access, and update your information. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">That&rsquo;s why we&rsquo;ve written this privacy policy. And it&rsquo;s why we&rsquo;ve tried to write it in a way that&rsquo;s blissfully free of the legalese that often clouds these documents, if you still have questions about anything in our privacy policy, just contact us. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>Information We Collect </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">There are three basic ways we collect information: Information you choose to give us.<br /> Information we get when you use our services. Information we get from third parties. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Here&rsquo;s a little more detail on each of these categories. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>Information You Choose to Give Us </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">When you interact with our services, we collect the information that you choose to share with us. For example, most of our services require you to set up a basic Matchon account, so we need to collect a few important details about you, such as: a unique user name you&rsquo;d like to go by, a password, an email address, a phone number, and your date of birth. To make it easier for others to find you, we may also ask you to provide us with some additional information that will be publicly visible on our services, such as profile pictures, a name, or other useful information. Other services, such as commerce products, may also require you to provide us with a debit or credit card number and its associated account information.Of course, you&rsquo;ll also provide us whatever information you send through the services. Keep in mind that the users you send texts, images, and any other content to can always save that content or copy it outside the app. So, the name common sense that applies to the Internet at large applies to Matchon as well: Don&rsquo;t send messages or share content that you wouldn&rsquo;t want someone to save or share. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">It probably goes without saying, but we&rsquo;ll say it anyway: When you contact Matchon Support or communicate with us in any other way, we&rsquo;ll collect whatever information you share. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>Information We Get When You Use Our Services </strong></span></span></span></p>
<p align="left"><a name="_GoBack"></a> <span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">When you use our services, we collect information about which of those services you&rsquo;ve used and how you&rsquo;ve used them. We might know, for instance, that you used one of the filter in app and the times you used this filter. Here&rsquo;s a fuller explanation of the type of information we collect when you use our services (to learn about how you can control some of this information, be sure to read the information section below): </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Usage Information- We collect information about your activity through our services. For example, we may collect information about:<br /> how you interact with the services, such as which filters you view or times apply to discover.<br /> how you communicate with other Matchon users, such as their names, the time and date of your communications, the number of messages you exchange with your friends which friends you exchange messages with the most, and your interactions with messages (such as when you open a message or capture a screenshot). </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Content Information -We collect information about the content you provide, such as if the recipient has viewed the content, and the metadata that is provided with the content.</span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Device Information- We collect device-specific information, such as the hardware model, operating system version, advertising identifier, unique application identifiers, unique device identifiers, browser type, language, wireless network, and mobile network information (including the mobile phone number).<br /> Device Phonebook- Because Matchon is all about communicating with friends, we may &mdash; with your consent &mdash; collect information from your device&rsquo;s phonebook, Camera and Photos. Many of our services require us to collect images and other information from your device&rsquo;s camera and photos. We&rsquo;ll access your camera and photos only after you give us your consent. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Location Information- When you use our services we may collect information about your location. With your consent, we may also collect information about your precise location using methods that include GPS, wireless networks, cell towers, Wi-Fi access points, and other sensors, such as gyroscopes, accelerometers, and compasses. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Information Collected by Cookies and Other Technologies. Like most online services and mobile applications, we may use cookies and other technologies, such as web beacons, web storage, and unique advertising identifiers, to collect information about your activity, browser, and device. We may also use these technologies to collect information when you interact with services we offer through one of our partners, such as commerce features. Most web browsers are set to accept cookies by default. If you prefer, you can usually remove or reject browser cookies through the settings on your browser or device. Keep in mind, though, that removing or rejecting cookies could affect the availability and functionality of our services. To learn more about how we use cookies and your choices, please check out our Cookie Statement. To learn more about how third parties use these technologies on our services, be sure to read the Analytics and Advertising Services Provided by Other sections of our privacy policy. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Log Information-We also collect log information when you use our website. That information includes, among other things: details about how you&rsquo;ve used our services.</span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>Information We Collect from Third Parties </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">We may collect information that other users provide about you when they use our services. For example, if another user allows us to collect information from their devices. Phonebook-and you&rsquo;re one of that user&rsquo;s contacts&mdash;we may combine the information we collect from that user&rsquo;s phonebook with other information we have collected about you. We may also obtain information from other companies that are owned or operated by us, or any other third-party sources, and combine that with the information we collect through our services. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>How We Use Information </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">What do we do with the information we collect? The short answer is: Provide you with an amazing set of products and services that we relentlessly improve. But we do a lot more as well such as: </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Develop, operate, improve, deliver, maintain, and protect our products and services ,communicate with you , monitor and analyze trends and usage , personalize the services by, among other things, suggesting friends or profile information , or customizing the content we show you, including ads. enhance the safety and security of our products and services, verify your identity and prevent fraud or other unauthorized or illegal activity, use information we&rsquo;ve collected from cookies and other technology to enhance the services and your experience with them, enforce our Terms of Service and other usage polices.<br /> We may also store some information locally on your device. For example, we may store information as local cache so that you can open the app and view content faster. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>How We Share Information </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">We may share information about you in the following ways:<br /> With other users. We may share the following information with other users:<br /> information about you, such as your username and name; information about how you have interacted with the services, such as the names of users you are friends with, and other information that will help users understand your connections with others using the services. For example, because it may not be clear whether a new friend request comes from someone you actually know, we may share whether you and the requestor have Matchon friends in common; any additional information you have consented for us to share. For example, when you let us access your device phonebook, we may share information about you with other users who have your phone number in their device phonebook; With all users and the general public. We may share the following information with all users as well as the general public: public information like your profile pictures that you submit to Local. If a Local service is streamed on the web or broadcast in some other media, it may be viewed by the public at large.<br /> With our affiliates- We may share information with entities within the Matchon family of companies With third parties- We may share your information with the following third parties:<br /> With service providers, sellers, and partners. We may share information about you with service providers who perform services on our behalf, sellers that provide goods through our services, and business partners that provide services and functionality.<br /> With third parties for legal reasons.-We may share information about you if we reasonably believe that disclosing the information is needed to: comply with any valid legal process, government request, or applicable law, rule, or regulation; investigate, remedy, or enforce potential Terms of Service violations; protect the rights, property, and safety of us, our users, or others; or<br /> detect and resolve any fraud or security concerns. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">With third parties as part of a merger or acquisition- If Matchon gets involved in a merger, asset sale, financing, liquidation or bankruptcy, or acquisition of all or some portion of our business to another company, we may share your information with that company before and after the transaction closes. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">In the aggregate or after de-identification.-We may also share with third parties, such as advertisers, aggregated or de-identified information that cannot reasonably be used to identify you. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>Information You Choose to Share with Third Parties </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">The services may also contain third-party links and search results, include third-party integrations, or be a co-branded or third-party-branded service that&rsquo;s being provided jointly with or by another company. By going to those links, using the third-party integration, or using a co-branded or third-party-branded service, you may be providing information (including personal information) directly to the third party, us, or both. You acknowledge and agree that we are not responsible for how those third parties collect or use your information. As always, we encourage you to review the privacy policies of every third-party website or service that you visit or use including those third parties you interact with through our services. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>How Long We Keep Your Content </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Matchon lets you text friends in chat room. On our end, that means that we automatically delete the content (the photo and video messages that you send your friends) from our servers.<br /> Finally &mdash; and this is important &mdash; you should understand that users who see the content you provide can always save it using any number of techniques: screenshots, in-app functionality, or any other image-capture technology. It&rsquo;s also possible, as with any digital information, that someone might be able to access messages forensically or find them in a device&rsquo;s temporary storage. Keep in mind that, while our systems are designed to carry out our deletion practices automatically, we cannot promise that deletion will occur within a specific timeframe. And we may also retain information in backup for a limited period of time or as required by law. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>Control over Your Information </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">We want you to be in control of your information, so we provide you with the following tools. Access and Updates. We strive to let you access and update most of the personal information that we have about you. There are limits though to the requests we&rsquo;ll accommodate. We may reject a request for a number of reasons, including, for example, that the request risks the privacy of other users, requires technical efforts that are disproportionate to the request, is repetitive, or is unlawful. You can access and update most of your basic account information right in app by visiting the app&rsquo;s Settings page. If you need to access, update, or delete any other personal information that we may have, you can put in a request here. Because your privacy is important to us, we may ask you to verify your identity or provide additional information before we let you access or update your personal information. We will try to update and access your information for free, but if it would require a disproportionate effort on our part, we may charge a fee. We will of course disclose the fee before we comply with your request.<br /> Revoking Permissions- If you change your mind about our ongoing ability to collect information from certain sources that you have already consented to, such as your phonebook, camera, photos, or location services, you can simply revoke your consent by changing the settings on your device if your device offers those options. Of course, if you do that, certain services may lose full functionality.<br /> Account Deletion. While we hope you&rsquo;ll remain a lifelong Matchon user, if for some reason you ever want to delete your account, just go here. If you ask to delete your account, you will have up to 30 days to restore your account before we delete your information from our servers. During this period of time, your account will not be visible to other Matchon users. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>Analytic and Advertising Services Provided by Others </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">We may let other companies use cookies, web beacons, and similar tracking technologies on the services. These companies may collect information about how you use the services and other websites and online services over time and across different services. This information may be used to, among other things, analyze and track data, determine the popularity of certain content, and better understand your online activity. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Additionally, some companies may use the information they collect on our services to deliver targeted advertisements on behalf of us or other companies, including on third-party websites and apps. Matchon does not currently respond to do-not-track signals that may be sent from your device. If we do so in the future, we will provide information about that practice in an updated version of this privacy policy. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>User inside India</strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Although we welcome MatchOn users from all over India, keep in mind that no matter where you live or where you happen to use our services, we operate our services from the India</span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>Children </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Our services are not intended for&mdash;and we don&rsquo;t direct them to&mdash;anyone under 18. </span></span></span></p>
<p align="justify"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>MODIFICATION</strong></span></span></span></p>
<p align="justify"><span style="font-size: medium;"><span style="font-size: small;">We reserve the right to determine and control all aspects (including all functionality) of the Services as well as the right to re-design, modify and remove any or all aspects of them. We may amend any of the terms and conditions contained in this Agreement at any time. Any changes will be effective upon the posting of such changes on the Application itself under terms and conditions,. All notice of changes to the Agreement will be posted for at least 30 (thirty) calendar days</span><span style="font-family: Calibri, serif;"><span style="font-size: small;">. </span></span></span></p>
<h2 class="western" align="justify"><strong><span style="color: #000000;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: small;">Disclaimer</span></span></span></strong></h2>
<p class="western"><br /> </p>
<p><span style="font-size: medium;"><strong>3 Ocean Entertainment LLP/ the Application disclaims that </strong></span><span style="font-size: small;">THE SERVICES, INCLUDING ALL CONTENT, SOFTWARE, FUNCTIONS, MATERIALS AND INFORMATION AVAILABLE OR PROVIDED IN CONNECTION WITH THE SERVICES, ARE PROVIDED "AS-IS." AS A USER OF THE SERVICES, YOU ACCESS AND USE THE APPLICATION, THE SERVICES AND ANY ONLINE PORTAL OR TOOL PROVIDED BY THE APPLICATIONAT YOUR OWN RISK. WE AND OUR AFFILIATES WAIVE AND DISCLAIM: (1) ANY REPRESENTATIONS, WARRANTIES, DECLARATIONS OR GUARANTEES REGARDING THIS AGREEMENT, THE SERVICES OR THE TRANSACTIONS CONTEMPLATED HEREBY, INCLUDING ANY IMPLIED WARRANTIES, DECLARATIONS OR GUARANTEES OF MERCHANTABILITY, VIABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT; (2) IMPLIED WARRANTIES ARISING OUT OF COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE; AND (3) ANY OBLIGATION, LIABILITY, RIGHT, CLAIM OR REMEDY IN TORT, WHETHER OR NOT ARISING FROM OUR NEGLIGENCE. </span></p>
<p><span style="font-size: small;">WE DO NOT WARRANT THAT THE FUNCTIONS, CONTACTS, CONTAINED IN THE DATING APP OR THE SERVICES WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE, TIMELY, SECURE, UNINTERRUPTED OR ERROR FREE.WE SHALL NOT BE LIABLE FOR UNAVAILIBILITY OF ANY SERVICES, CONTACTS OR SERVICE INTERRUPTIONS, INCLUDING, BUT NOT LIMITED TO SYSTEM FAILURES OR OTHER INTERRUPTIONS THAT MAY AFFECT THE ONLINE DATING COMMUNICATION/ EXPERIENCE, RECEIPT, PROCESSING, ACCEPTANCE, COMPLETION OR SETTLEMENT OF ANY TRANSACTION. SOME JURISDICTIONS' LAWS DO NOT ALLOW EXCLUSION OF AN IMPLIED WARRANTY, IN WHICH CASE THE FOREGOING DISCLAIMER MAY NOT APPLY TO YOU, AND WE AND OUR AFFILIATES DISCLAIM TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON- INFRINGEMENT OR QUIET ENJOYMENT.</span></p>
<p class="western"><br /> </p>
</body>
</html>
