<html>
<head></head>
<body>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>Terms of Service </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>Welcome to Matchon! </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">We've drafted these Terms of Service (which we simply call the "Terms") so that you</span></span><span style="font-family: SimSun, serif;"><span style="font-size: small;">&rsquo;</span></span><span style="font-family: Calibri, serif;"><span style="font-size: small;">ll know the rules that govern our relationship with you. Although we have tried our best to strip the legalese from the Terms, may still read like a traditional contract.<br /> There </span></span><span style="font-family: SimSun, serif;"><span style="font-size: small;">i</span></span><span style="font-family: Calibri, serif;"><span style="font-size: small;">s a good reason for that: These Terms do indeed form a legally binding contract between you and Matchon . So please read them carefully. By using the Services, you agree to the Terms. If you don't agree with them then don't use the Services. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Arbitration notice: we want to let you know upfront that these terms contain an arbitration clause a little later on. Except for certain types of disputes mentioned in that arbitration clause, you and Matchon agree that disputes between us will be resolved by mandatory binding arbitration, and you and Matchon waive any right to participate in a class-action lawsuit or class-wide arbitration. </span></span></span></p>
<p align="left">⚫<span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>Who Can Use the Services<br /> </strong></span></span><span style="font-family: Calibri, serif;"><span style="font-size: small;">No one under 18 is allowed to create an account or use the Services. We may offer additional Services with additional terms that may require you to be even older to. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Matchon is devoted to providing global users with a real-time video chat platform to find and create diversified novel interactive contents through online video chat. To maintain healthy and safe real-time video chat on Matchon platform, a series of community conventions are established to ensure good user experience. We make utmost efforts to keep Matchon safe in all aspects; however, no 100% assurance exists given a lot of objective conditions. Any user's breach of following terms and rules may lead to suspension of our services and even permanent ban. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">It should also be noted that, if applicable, we'll have the right to tell on any suspected criminal act to local public security organ. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Arial, serif;"><strong>1. </strong></span><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>No Violence and/or Self-mutilation </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Security is of top priority with Matchon. We take any act involving in forced threat and self-mutilation seriously. If we find any risk of destruction or immediate threat against public security, we'll delete such offensive contents and report them to enforcement agency. Also, threat against others is absolutely intolerant, or else the offender will be permanently banned from using Matchon services. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Arial, serif;"><strong>2. </strong></span><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>No Nudity or Broad Words &amp; Acts </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Any user in front of the lens must be dressed modestly. Any user who is video-chatting in a dubious manner will be suspended or permanently banned from Matchon service. User is prohibited showing up body that should be hidden by dress. Matchon prohibits seducing nudity in the name of any person, any offender upon discovery will be provisionally or permanently banned from Matchon services. Female user must keep bosom moderately dressed, or else she will be provisionally or permanently banned from Matchon services. The user is prohibited from: Using vulgar, offensive or broad words in front of the lens or in real-time video chat; Showing his/her or other's offensive or pornographic video; Having sex or sex implication, or showing sex doll or sexual or dance actions; </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Arial, serif;"><strong>3. </strong></span><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>No Fraud, Harassment or Hatred Comments </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">The user must respect other members of the community. It's intolerant for Matchon of ridicule, fraud, racism or harassment against other users in the community. We do regard free speech, but we do not permit personal abuse based on race, nationality, religion, sex, gender, sexual orientation, disability or other illness. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Arial, serif;"><strong>4. </strong></span><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>No Use of Prohibited Goods<br /> </strong></span></span><span style="font-family: Calibri, serif;"><span style="font-size: small;">Live use of prohibited goods, doping items or smoking or drug or drinking is forbidden. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Arial, serif;"><strong>5. </strong></span><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>No Use by Minor </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Matchon is designed for users over 18 years old, minors under this age are banned from live access, and we'll close video chat services to minor users. Cover girl/boy is not allowed. Minor live object is not allowed. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Arial, serif;"><strong>6. </strong></span><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>No Publication of Personal Contact Information </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Unauthorized publication of other's personal information is forbidden, including but not limited to email address, telephone number or residence. Also, you're seriously reminded of protecting your personal information and preventing them from unintentional disclosure. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Arial, serif;"><strong>7. </strong></span><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>No Trick on Emergency Organ or Hotline<br /> </strong></span></span><span style="font-family: Calibri, serif;"><span style="font-size: small;">It is absolutely forbidden to play trick on emergency organ or hotline. Any user in connection with the said behavior will be permanently banned from Matchon services. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Arial, serif;"><strong>8. </strong></span><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>No Inducing or Instigating Violation of Rules </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Any inducement of sexual behavior or illegal behavior of community member is forbidden. Also, any guiding or manipulating other members to produce pornographic picture and video or solicit personal information is forbidden.<br /> Moreover, we forbid illegal business activity, including but not limited to multilevel marketing. We forbid instigating violation of rules, no matter during chat or in real-time video chat. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Arial, serif;"><strong>9. </strong></span><span style="font-family: Calibri, serif;"><span style="font-size: small;"><strong>No Spam Message </strong></span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">Any action preventing normal and orderly chat of other users by repeated entry or in other way is forbidden. Likewise, publicity of pornographic, obscene or malicious website link is forbidden. Matchon reserves the right to dispose of any account involving in the above behavior. </span></span></span></p>
<p align="left"><span style="font-size: medium;"><span style="font-family: Arial, serif;"><strong>10. Paid performing arts services</strong></span></span></p>
<p align="left"><a name="_GoBack"></a> <span style="font-size: medium;"><span style="font-family: Calibri, serif;"><span style="font-size: small;">The services provided by this software include free services and paid performing arts services by hostess .Users can purchase paid services through payment methods. The specific methods are: users purchase membership services and virtual currency (gold coins) of the software platform through Google Pay and other payment methods and then purchase the charges that users want to use in accordance with the tariff standards published by the software.&nbsp; Service, so as to obtain the right to use the corresponding charged service.&nbsp; Users spend gold coins to exchange gifts, audio and other services to other designated users on the platform. The software will give the user a clear prompt before using it. Only when the user confirms that he agrees to pay the fee according to the aforementioned payment method and completes the payment according to the prompt, the user can use the paid service.&nbsp;Part of the income from voice calls/audio calls will be given to actors. As long as the user continues to operate through the payment prompt, it means that the user agrees to the charging standard. And the system will not refund any payment done on this application.</span></span></span></p>
<p align="left"><br /> </p>
<p align="left"><br /> </p>
</body>
</html>
